import { compile, type JSONSchema } from 'json-schema-to-typescript';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SCHEMAS_DIR = path.resolve(__dirname, '../v1');
const TARGET_FILE = path.resolve(__dirname, '../../protocol/src/generated/types.ts');

const SCHEMA_FILES = [
  'capability.json',
  'security-scope.json',
  'tool-passport.json',
  'error.json',
  'action.json',
  'decision.json',
  'approval.json',
  'agent-run.json',
  'verification.json',
  'evidence.json',
  'audit-event.json',
  'checkpoint.json',
  'finding.json',
  'events.json',
  'protocol-envelope.json',
  'benchmark-result.json',
];

async function generate() {
  const isCheck = process.argv.includes('--check');

  const definitions: Record<string, JSONSchema> = {};

  for (const file of SCHEMA_FILES) {
    const fullPath = path.join(SCHEMAS_DIR, file);
    if (!fs.existsSync(fullPath)) {
      console.error(`Error: Schema file not found: ${fullPath}`);
      process.exit(1);
    }
    const content = JSON.parse(fs.readFileSync(fullPath, 'utf-8')) as JSONSchema;
    const typeName = (content as Record<string, unknown>).title as string || path.basename(file, '.json');
    definitions[typeName] = content;
  }

  // Construct master schema referencing all types
  const masterSchema: JSONSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'ValutxProtocolBundle',
    type: 'object',
    definitions: {},
    properties: {},
  };

  for (const [name, schema] of Object.entries(definitions)) {
    // Clone schema and replace relative $ref: "capability.json" with "#/definitions/Capability"
    const schemaStr = JSON.stringify(schema).replace(/"capability\.json"/g, '"#/definitions/Capability"');
    if (masterSchema.definitions) {
      masterSchema.definitions[name] = JSON.parse(schemaStr) as JSONSchema;
    }
    if (masterSchema.properties) {
      masterSchema.properties[name] = { $ref: `#/definitions/${name}` };
    }
  }

  let output = await compile(masterSchema, 'ValutxProtocolBundle', {
    bannerComment: `/* eslint-disable */
/**
 * AUTO-GENERATED BY VALUTX CODEGEN - DO NOT EDIT MANUALLY
 * SOURCE: packages/schemas/v1/
 */
`,
    style: {
      singleQuote: true,
      semi: true,
    },
    additionalProperties: false,
  });

  // Remove the wrapper master bundle interface if present, keeping all exported types
  output = output.replace(/export interface ValutxProtocolBundle \{[\s\S]*?\n\}/, '');

  // Ensure target directory exists
  const targetDir = path.dirname(TARGET_FILE);
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  if (isCheck) {
    if (!fs.existsSync(TARGET_FILE)) {
      console.error(`Check failed: Target file ${TARGET_FILE} does not exist.`);
      process.exit(1);
    }
    const existing = fs.readFileSync(TARGET_FILE, 'utf-8');
    if (existing.trim() !== output.trim()) {
      console.error(`Check failed: Generated types are stale. Run 'pnpm run generate:ts' to update.`);
      process.exit(1);
    }
    console.log(`✓ TypeScript codegen is up to date.`);
    return;
  }

  fs.writeFileSync(TARGET_FILE, output, 'utf-8');
  console.log(`✓ Generated TypeScript definitions written to ${TARGET_FILE}`);
}

generate().catch((err) => {
  console.error('Failed to generate TypeScript types:', err);
  process.exit(1);
});
