// AUTO-GENERATED BY VALUTX CODEGEN - DO NOT EDIT MANUALLY
// SOURCE: packages/schemas/v1/

#![allow(missing_docs)]
#![allow(non_camel_case_types)]

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

/// Protocol version identifier
pub const PROTOCOL_VERSION: &str = "1.0.0";

/// Canonical capability taxonomy for VaultX 2.0 privilege enforcement
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Capability {
    #[serde(rename = "project.read")]
    ProjectRead,
    #[serde(rename = "project.write")]
    ProjectWrite,
    #[serde(rename = "terminal.execute")]
    TerminalExecute,
    #[serde(rename = "process.spawn")]
    ProcessSpawn,
    #[serde(rename = "network.external")]
    NetworkExternal,
    #[serde(rename = "network.lab")]
    NetworkLab,
    #[serde(rename = "cyber.scan")]
    CyberScan,
    #[serde(rename = "cyber.active_scan")]
    CyberActiveScan,
    #[serde(rename = "secrets.use")]
    SecretsUse,
    #[serde(rename = "plugin.install")]
    PluginInstall,
    #[serde(rename = "policy.edit")]
    PolicyEdit,
    #[serde(rename = "audit.export")]
    AuditExport,
    #[serde(rename = "checkpoint.restore")]
    CheckpointRestore,
    #[serde(rename = "background_agent")]
    BackgroundAgent,
    #[serde(rename = "deploy.execute")]
    DeployExecute,
}

/// Cryptographically verifiable scope envelope for authorized cybersecurity lab and scan operations
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SecurityScope {
    pub id: Uuid,
    pub name: String,
    pub allowed_domains: Vec<String>,
    pub allowed_cidrs: Vec<String>,
    pub allowed_ports: Vec<u16>,
    pub max_depth: u32,
    pub created_by: String,
    pub expires_at: DateTime<Utc>,
    pub scope_hash: String,
}

/// Tool runtime execution environment
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RuntimeType {
    HostBinary,
    Container,
    Wsl,
    Script,
}

/// Cryptographically signed manifest defining an authorized tool and its sandboxing constraints
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ToolPassport {
    pub id: Uuid,
    pub name: String,
    pub version: String,
    pub description: String,
    pub sha256: String,
    pub capabilities: Vec<Capability>,
    pub runtime_type: RuntimeType,
    pub sandbox_profile: String,
    pub memory_limit_mb: u32,
    pub cpu_quota_pct: u32,
    pub timeout_seconds: u32,
}

/// Stable machine-readable error codes across VaultX boundaries
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ErrorCode {
    POLICY_DENIED,
    SCOPE_DENIED,
    SANDBOX_UNAVAILABLE,
    TOOL_NOT_FOUND,
    APPROVAL_REQUIRED,
    VERIFICATION_FAILED,
    RESOURCE_LIMIT,
    PROTOCOL_VIOLATION,
    INTERNAL_ERROR,
}

/// Structured machine-readable error format across VaultX 2.0 user and IPC boundaries
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProtocolError {
    pub code: ErrorCode,
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<HashMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remediation: Option<String>,
}

/// Privileged operation requested by untrusted agent runtime, evaluated by policy engine
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActionRequest {
    pub id: Uuid,
    pub run_id: Uuid,
    pub project_id: Uuid,
    pub capability: Capability,
    pub tool_name: String,
    pub params: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub security_scope_id: Option<Uuid>,
    pub action_hash: String,
    pub requested_at: DateTime<Utc>,
}

/// Policy evaluation effect
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DecisionEffect {
    ALLOW,
    DENY,
    APPROVAL_REQUIRED,
}

/// Deterministic policy evaluation outcome for an ActionRequest
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Decision {
    pub id: Uuid,
    pub action_id: Uuid,
    pub effect: DecisionEffect,
    pub policy_id: String,
    pub reasons: Vec<String>,
    pub constraints: HashMap<String, String>,
    pub evaluated_at: DateTime<Utc>,
}

/// Approval decision outcome
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ApprovalDecision {
    APPROVED,
    REJECTED,
}

/// Canonical roles authorized to approve actions
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ApproverRole {
    Owner,
    Admin,
    #[serde(rename = "Security Admin")]
    SecurityAdmin,
    Developer,
    #[serde(rename = "Security Analyst")]
    SecurityAnalyst,
    Researcher,
    Student,
    Viewer,
    Auditor,
}

/// Cryptographically signed human or authority authorization bound to an action hash
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Approval {
    pub id: Uuid,
    pub action_id: Uuid,
    pub action_hash: String,
    pub decision: ApprovalDecision,
    pub approver_id: String,
    pub approver_role: ApproverRole,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub timestamp: DateTime<Utc>,
    pub signature: String,
}

/// Agent execution lifecycle status
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RunStatus {
    INITIALIZING,
    RUNNING,
    PAUSED_FOR_APPROVAL,
    COMPLETED,
    FAILED,
    ROLLED_BACK,
    CANCELLED,
}

/// Lifecycle state and metadata for an agent execution task
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AgentRun {
    pub id: Uuid,
    pub project_id: Uuid,
    pub task_id: Uuid,
    pub status: RunStatus,
    pub goal: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checkpoint_id: Option<Uuid>,
}

/// Verification status
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum VerificationStatus {
    PASSED,
    FAILED,
}

/// Verification check detail
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerificationCheck {
    pub name: String,
    pub passed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    pub duration_ms: u64,
}

/// Deterministic post-execution verification outcome for code and state mutations
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerificationResult {
    pub id: Uuid,
    pub run_id: Uuid,
    pub status: VerificationStatus,
    pub checks: Vec<VerificationCheck>,
    pub created_at: DateTime<Utc>,
}

/// Evidence artifact
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvidenceArtifact {
    pub path: String,
    pub sha256: String,
    pub size_bytes: u64,
}

/// Cryptographically verifiable bundle of proof recording execution outputs and side effects
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Evidence {
    pub id: Uuid,
    pub run_id: Uuid,
    pub action_id: Uuid,
    pub sha256: String,
    pub artifacts: Vec<EvidenceArtifact>,
    pub timestamp: DateTime<Utc>,
}

/// Audit actor
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AuditActor {
    pub id: String,
    pub role: String,
}

/// Server-side hash-chained tamper-evident audit log entry
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AuditEvent {
    pub id: Uuid,
    pub sequence: u64,
    pub event_type: String,
    pub timestamp: DateTime<Utc>,
    pub actor: AuditActor,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub run_id: Option<Uuid>,
    pub payload: serde_json::Value,
    pub prev_hash: String,
    pub hash: String,
    pub signature: String,
}

/// Deterministic repository state checkpoint enabling automated rollback
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Checkpoint {
    pub id: Uuid,
    pub project_id: Uuid,
    pub run_id: Uuid,
    pub git_commit_sha: String,
    pub rollback_point: bool,
    pub description: String,
    pub created_at: DateTime<Utc>,
}

/// Finding severity level
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum FindingSeverity {
    CRITICAL,
    HIGH,
    MEDIUM,
    LOW,
    INFO,
}

/// Structured cybersecurity or code quality finding bound to cryptographic evidence
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Finding {
    pub id: Uuid,
    pub run_id: Uuid,
    pub title: String,
    pub severity: FindingSeverity,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwe: Option<String>,
    pub target: String,
    pub description: String,
    pub evidence_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remediation: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// Lifecycle event types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventType {
    RunCreated,
    PlanCreated,
    ApprovalRequested,
    ApprovalGranted,
    ToolStarted,
    ToolOutput,
    PolicyDenied,
    SandboxStarted,
    VerificationStarted,
    VerificationPassed,
    VerificationFailed,
    EvidenceCreated,
    RunCompleted,
    RunRolledBack,
}

/// Lifecycle event telemetry stream emitted across runtime, agent, and user boundaries
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProtocolEvent {
    pub event_id: Uuid,
    pub run_id: Uuid,
    pub timestamp: DateTime<Utc>,
    #[serde(rename = "type")]
    pub event_type: EventType,
    pub data: serde_json::Value,
}

/// Envelope message types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageType {
    NegotiateRequest,
    NegotiateResponse,
    ActionRequest,
    Decision,
    Approval,
    AgentRun,
    VerificationResult,
    Evidence,
    AuditEvent,
    Checkpoint,
    Finding,
    ProtocolEvent,
    ProtocolError,
}

/// Negotiation status
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NegotiationStatus {
    REQUEST,
    ACCEPTED,
    REJECTED,
}

/// Protocol negotiation details
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProtocolNegotiation {
    pub client_supported_versions: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub selected_version: Option<String>,
    pub status: NegotiationStatus,
}

/// Standardized wire message envelope with version negotiation and message routing metadata
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProtocolEnvelope {
    pub protocol_version: String,
    pub message_id: Uuid,
    pub timestamp: DateTime<Utc>,
    pub sender: String,
    pub recipient: String,
    pub message_type: MessageType,
    pub payload: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub negotiation: Option<ProtocolNegotiation>,
}

/// Schema for VaultX-Bench task execution outcome and governance metrics
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BenchmarkResult {
    pub run_id: Uuid,
    pub task_id: String,
    pub benchmark_version: String,
    pub success: bool,
    pub verified: bool,
    pub policy_denials: u64,
    pub blocks: u64,
    pub rollback_ok: bool,
    pub approvals_count: u64,
    pub wall_time_ms: u64,
    pub cost_usd: f64,
    pub created_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}
