use std::fs;
use std::path::PathBuf;

#[test]
fn test_protocol_codegen_header_and_staleness() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let generated_rs = manifest_dir
        .join("src")
        .join("protocol")
        .join("generated.rs");
    assert!(generated_rs.exists(), "protocol/generated.rs must exist");

    let content = fs::read_to_string(&generated_rs).expect("read generated.rs");
    assert!(
        content.contains("AUTO-GENERATED BY VALUTX CODEGEN - DO NOT EDIT MANUALLY"),
        "generated.rs must contain the auto-generated banner header"
    );
    assert!(
        content.contains("SOURCE: packages/schemas/v1/"),
        "generated.rs must document source directory"
    );

    // Ensure all 15 schemas exist in source
    let schemas_dir = manifest_dir
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("packages")
        .join("schemas")
        .join("v1");

    let expected_schemas = [
        "capability.json",
        "security-scope.json",
        "tool-passport.json",
        "error.json",
        "action.json",
        "decision.json",
        "approval.json",
        "agent-run.json",
        "verification.json",
        "evidence.json",
        "audit-event.json",
        "checkpoint.json",
        "finding.json",
        "events.json",
        "protocol-envelope.json",
    ];

    for schema in expected_schemas {
        let schema_path = schemas_dir.join(schema);
        assert!(
            schema_path.exists(),
            "Expected schema file {:?} does not exist",
            schema_path
        );
    }
}
